app/main/default/objects/BigQuery_Export__c/BigQuery_Export__c.object-meta.xml
<CustomObject>
    <description>Each export is a schedule of objects to push into BigQuery.</description>
    <label>BigQuery Export</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BigQuery Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/BigQuery_Export__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily at 12am</fullName>
            </value>
            <value>
                <fullName>Daily at 1am</fullName>
            </value>
            <value>
                <fullName>Daily at 2am</fullName>
            </value>
            <value>
                <fullName>Daily at 3am</fullName>
            </value>
            <value>
                <fullName>Daily at 4am</fullName>
            </value>
            <value>
                <fullName>Daily at 5am</fullName>
            </value>
            <value>
                <fullName>Daily at 6am</fullName>
            </value>
            <value>
                <fullName>Daily at 7am</fullName>
            </value>
            <value>
                <fullName>Daily at 8am</fullName>
            </value>
            <value>
                <fullName>Daily at 9am</fullName>
            </value>
            <value>
                <fullName>Daily at 10am</fullName>
            </value>
            <value>
                <fullName>Daily at 11am</fullName>
            </value>
            <value>
                <fullName>Daily at 12pm</fullName>
            </value>
            <value>
                <fullName>Daily at 1pm</fullName>
            </value>
            <value>
                <fullName>Daily at 2pm</fullName>
            </value>
            <value>
                <fullName>Daily at 3pm</fullName>
            </value>
            <value>
                <fullName>Daily at 4pm</fullName>
            </value>
            <value>
                <fullName>Daily at 5pm</fullName>
            </value>
            <value>
                <fullName>Daily at 6pm</fullName>
            </value>
            <value>
                <fullName>Daily at 7pm</fullName>
            </value>
            <value>
                <fullName>Daily at 8pm</fullName>
            </value>
            <value>
                <fullName>Daily at 9pm</fullName>
            </value>
            <value>
                <fullName>Daily at 10pm</fullName>
            </value>
            <value>
                <fullName>Daily at 11pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/BigQuery_Export_Log__c/BigQuery_Export_Log__c.object-meta.xml
<CustomObject>
    <label>BigQuery Export Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BigQuery Export Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/BigQuery_Export_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful object export</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/BigQuery_Export_Object__c.object-meta.xml
<CustomObject>
    <description>Information about each object that will get sent to BigQuery for a given export schedule.</description>
    <label>BigQuery Export Object</label>
    <nameField>
        <displayFormat>BQXO-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BigQuery Export Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/main/default/objects/BigQuery_Export_Object__c/fields/BigQuery_Export__c.field-meta.xml
<CustomField>
    <fullName>BigQuery_Export__c</fullName>
    <description>The BigQuery Export (schedule) that this object will be exported to BigQuery on.</description>
    <label>BigQuery Export</label>
    <referenceTo>BigQuery_Export__c</referenceTo>
    <relationshipLabel>BigQuery Export Objects</relationshipLabel>
    <relationshipName>BigQuery_Export_Objects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Dataset_ID__c.field-meta.xml
<CustomField>
    <fullName>Dataset_ID__c</fullName>
    <description>The BigQuery Dataset where this data will be exported to.</description>
    <inlineHelpText>The BigQuery Dataset where this data will be exported to.</inlineHelpText>
    <label>Dataset ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The object name is extracted from the SOQL query.</description>
    <inlineHelpText>The object that will be exported.</inlineHelpText>
    <label>Object</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <description>The BigQuery Project ID where the object data will be exported to.</description>
    <inlineHelpText>The BigQuery Project ID where the object data will be exported to.</inlineHelpText>
    <label>Project ID</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The SOQL query to run when exporting this object</description>
    <inlineHelpText>The SOQL query to run when exporting this object</inlineHelpText>
    <label>Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Table_ID__c.field-meta.xml
<CustomField>
    <fullName>Table_ID__c</fullName>
    <description>The BigQuery Table ID that this data will be exported to.</description>
    <inlineHelpText>The BigQuery Table ID that this data will be exported to.</inlineHelpText>
    <label>Table ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/classes/BigQueryExportScheduleTest.cls
@isTest(SeeAllData=false)
public class BigQueryExportScheduleTest {
    
    public static String CRON_EXP = '0 0 1 * * ? 2022';
    
    

    testMethod static void testSchedule() {
        Account acc = new Account(
        	Name = 'Test Account'
        );
        
        insert acc;
        
        BigQuery_Export__c bqe = new BigQuery_Export__c(
        	Name = 'Export Schedule',
            Schedule__c = 'Daily at 1am'
        );
        
        Database.SaveResult bqeSave = Database.insert(bqe, false);
        
        BigQuery_Export_Object__c bqxo = new BigQuery_Export_Object__c(
            BigQuery_Export__c = bqeSave.getId(),
            Object__c = 'Account',
            Project_ID__c = 'my-project',
            Dataset_ID__c = 'my-dataset',
            Table_ID__c = 'my-table',
            Query__c = 'SELECT Id, Name FROM Account'
        );
        
        Database.SaveResult bqxoSave = Database.insert(bqxo, false);
        
        
        GoogleBigQueryRequestMock fakeResponse = new GoogleBigQueryRequestMock(200,
                                                 'Complete',
                                                 '{ "access_token": "access_token" }',
                                                 null);
		Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        // Batch
        Test.startTest();
        BigQueryExportSchedule sched = new BigQueryExportSchedule();
        String jobId = System.schedule('testBigQueryExportSchedule', CRON_EXP, sched);
        sched.execute(null);
        Test.stopTest();
        
        List<BigQuery_Export_Log__c> logs = [SELECT Id, Name, Type__c, Message__c FROM BigQuery_Export_Log__c];
        
        System.debug(logs);
        System.assertEquals(1, logs.size());
        System.assertEquals('Successful object export', logs[0].Type__c);
    }
    
}