app/main/default/objects/BigQuery_Export_Log__c/BigQuery_Export_Log__c.object-meta.xml
<CustomObject>
    <label>BigQuery Export Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BigQuery Export Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/BigQuery_Export_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful object export</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/BigQuery_Export_Object__c.object-meta.xml
<CustomObject>
    <description>Information about each object that will get sent to BigQuery for a given export schedule.</description>
    <label>BigQuery Export Object</label>
    <nameField>
        <displayFormat>BQXO-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BigQuery Export Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

app/main/default/objects/BigQuery_Export_Object__c/fields/Dataset_ID__c.field-meta.xml
<CustomField>
    <fullName>Dataset_ID__c</fullName>
    <description>The BigQuery Dataset where this data will be exported to.</description>
    <inlineHelpText>The BigQuery Dataset where this data will be exported to.</inlineHelpText>
    <label>Dataset ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Last_Run_Finished__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Finished__c</fullName>
    <label>Last Run Finished</label>
    <type>DateTime</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Last_Run_Start__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Start__c</fullName>
    <label>Last Run Start</label>
    <type>DateTime</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The object name is extracted from the SOQL query.</description>
    <inlineHelpText>The object that will be exported.</inlineHelpText>
    <label>Object</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Project_ID__c.field-meta.xml
<CustomField>
    <fullName>Project_ID__c</fullName>
    <description>The BigQuery Project ID where the object data will be exported to.</description>
    <inlineHelpText>The BigQuery Project ID where the object data will be exported to.</inlineHelpText>
    <label>Project ID</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The SOQL query to run when exporting this object</description>
    <inlineHelpText>The SOQL query to run when exporting this object</inlineHelpText>
    <label>Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

app/main/default/objects/BigQuery_Export_Object__c/fields/Table_ID__c.field-meta.xml
<CustomField>
    <fullName>Table_ID__c</fullName>
    <description>The BigQuery Table ID that this data will be exported to.</description>
    <inlineHelpText>The BigQuery Table ID that this data will be exported to.</inlineHelpText>
    <label>Table ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

app/main/default/classes/BigQueryExportBatch.cls
/**
 * BigQuery Exporter Batch
 * 
 * This batch takes a single BigQuery Export and processes the child objects as a batch each (in series)
 */
global class BigQueryExportBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

    private BigQuery_Export_Object__c bqxo;
    
    /**
     * Constructor
     */
    global BigQueryExportBatch(BigQuery_Export_Object__c bqxo) {
        this.bqxo = bqxo;
    }
    
    /**
     * Run the query
     */
	global Database.QueryLocator start(Database.BatchableContext BC){
        Database.QueryLocator ql;
        Id bqxoid = this.bqxo.Id;

        // If a job is already running, then exit:
        if (this.bqxo.Job_ID__c != null) {
            return null;
        }
        
        try {
	        ql = Database.getQueryLocator(this.bqxo.Query__c);
            this.bqxo.Job_ID__c = BC.getJobId();
            this.bqxo.Last_Run_Start__c = DateTime.now();
            update this.bqxo;
        } catch(Exception e) {
            BigQuery_Export_Log__c l = new BigQuery_Export_Log__c(
	            Type__c = 'Error',
				Message__c = e.getMessage(),
				Name = this.bqxo.Object__c + ' batch start error'
    	    );
	        insert l;
            System.debug(e);
            return null;
        }

        return ql;
	}

    /**
     * Send a portion (a batch) of records to BigQuery
     */
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		// InsertAll
		BigQueryExportJob job = new BigQueryExportJob(this.bqxo.Project_ID__c, this.bqxo.Dataset_ID__c, this.bqxo.Table_ID__c);
        job.rows = scope;
		BigQueryExportJob run = BigQueryExportController.runJob(job);

        // Log errors
        if (!run.success) {
            BigQuery_Export_Log__c l = new BigQuery_Export_Log__c(
            	Type__c = 'Error',
                Message__c = run.response,
                Name = this.bqxo.Object__c + ' failed to export batch'
            );
            insert l;
        }
	}

    /**
     * This batch is done, let's queue up the next object in this batch run
     */
	global void finish(Database.BatchableContext BC){
        this.bqxo.Job_ID__c = null;
        this.bqxo.Last_Run_Finished__c = DateTime.now();
        update bqxo;
        
        BigQuery_Export_Log__c l = new BigQuery_Export_Log__c(
            Type__c = 'Successful object export',
			Message__c = BC.getJobId() + ' finished at ' + DateTime.now(),
			Name = this.bqxo.Object__c + ' exported successfully'
        );
        insert l;
	}
    
}